<?php
require_once '../../config/config.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports Dashboard - Softpro Skill Solutions</title>
    <link rel="stylesheet" href="<?php echo $base_url; ?>assets/css/style.css">
    <link rel="stylesheet" href="<?php echo $base_url; ?>assets/css/report.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <?php include '../../components/topbar.php'; ?>
    <?php include '../../components/sidebar.php'; ?>

    <!-- Main Content -->
    <main class="main-content">
        <div class="container">
            <div class="page-header">
                <h1>Reports Dashboard</h1>
                <div class="header-actions">
                    <button class="btn btn-primary" onclick="window.location.href='generate.php'">
                        <i class="fas fa-plus"></i>
                        Generate New Report
                    </button>
                </div>
            </div>

            <!-- Report Categories -->
            <div class="report-categories">
                <div class="category-card">
                    <h3>Attendance Reports</h3>
                    <ul class="report-list">
                        <li>
                            <a href="attendance-report.php">
                                <i class="fas fa-calendar-check"></i>
                                Monthly Attendance Report
                            </a>
                        </li>
                        <li>
                            <a href="attendance-report.php?type=daily">
                                <i class="fas fa-calendar-day"></i>
                                Daily Attendance Report
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="category-card">
                    <h3>Performance Reports</h3>
                    <ul class="report-list">
                        <li>
                            <a href="performance-report.php">
                                <i class="fas fa-chart-line"></i>
                                Student Performance Report
                            </a>
                        </li>
                        <li>
                            <a href="program-effectiveness-report.php">
                                <i class="fas fa-graduation-cap"></i>
                                Program Effectiveness Report
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="category-card">
                    <h3>Financial Reports</h3>
                    <ul class="report-list">
                        <li>
                            <a href="financial-report.php">
                                <i class="fas fa-money-bill-wave"></i>
                                Monthly Financial Report
                            </a>
                        </li>
                        <li>
                            <a href="financial-analysis-report.php">
                                <i class="fas fa-chart-pie"></i>
                                Financial Analysis Report
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="category-card">
                    <h3>Center & Partner Reports</h3>
                    <ul class="report-list">
                        <li>
                            <a href="training-center-report.php">
                                <i class="fas fa-school"></i>
                                Training Center Report
                            </a>
                        </li>
                        <li>
                            <a href="training-partner-report.php">
                                <i class="fas fa-building"></i>
                                Training Partner Report
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- Recent Reports -->
            <div class="recent-reports">
                <h2>Recent Reports</h2>
                <div class="table-responsive">
                    <table class="data-table">
                        <thead>
                            <tr>
                                <th>Report Name</th>
                                <th>Generated On</th>
                                <th>Generated By</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Monthly Attendance Report - April 2024</td>
                                <td>01 May 2024, 11:45 AM</td>
                                <td>John Doe</td>
                                <td>
                                    <a href="attendance-report.php" class="btn btn-sm btn-primary">View</a>
                                    <button class="btn btn-sm btn-secondary">Download</button>
                                </td>
                            </tr>
                            <tr>
                                <td>Student Performance Report - Q1 2024</td>
                                <td>30 Apr 2024, 03:30 PM</td>
                                <td>Jane Smith</td>
                                <td>
                                    <a href="performance-report.php" class="btn btn-sm btn-primary">View</a>
                                    <button class="btn btn-sm btn-secondary">Download</button>
                                </td>
                            </tr>
                            <tr>
                                <td>Financial Report - March 2024</td>
                                <td>01 Apr 2024, 10:15 AM</td>
                                <td>Mike Johnson</td>
                                <td>
                                    <a href="financial-report.php" class="btn btn-sm btn-primary">View</a>
                                    <button class="btn btn-sm btn-secondary">Download</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>

    <script src="<?php echo $base_url; ?>assets/js/main.js"></script>
</body>
</html> 