<?php
require_once '../../config/config.php';

// Get report parameters
$type = $_GET['type'] ?? '';
$start_date = $_GET['start_date'] ?? '';
$end_date = $_GET['end_date'] ?? '';
$program = $_GET['program'] ?? '';
$batch = $_GET['batch'] ?? '';
$format = $_GET['format'] ?? 'html';

// Set report title based on type
$report_title = 'Report';
switch ($type) {
    case 'attendance-monthly':
        $report_title = 'Monthly Attendance Report';
        break;
    case 'attendance-daily':
        $report_title = 'Daily Attendance Report';
        break;
    case 'performance-student':
        $report_title = 'Student Performance Report';
        break;
    case 'performance-program':
        $report_title = 'Program Effectiveness Report';
        break;
    case 'financial-monthly':
        $report_title = 'Monthly Financial Report';
        break;
    case 'financial-analysis':
        $report_title = 'Financial Analysis Report';
        break;
    case 'center':
        $report_title = 'Training Center Report';
        break;
    case 'partner':
        $report_title = 'Training Partner Report';
        break;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $report_title; ?> - Softpro Skill Solutions</title>
    <link rel="stylesheet" href="<?php echo $base_url; ?>assets/css/style.css">
    <link rel="stylesheet" href="<?php echo $base_url; ?>assets/css/report.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <?php include '../../components/topbar.php'; ?>
    <?php include '../../components/sidebar.php'; ?>

    <!-- Main Content -->
    <main class="main-content">
        <div class="container">
            <div class="page-header">
                <h1><?php echo $report_title; ?></h1>
                <div class="header-actions">
                    <button class="btn btn-secondary" onclick="window.location.href='generate.php'">
                        <i class="fas fa-arrow-left"></i>
                        Back to Generate
                    </button>
                    <button class="btn btn-primary" onclick="window.print()">
                        <i class="fas fa-print"></i>
                        Print Report
                    </button>
                    <button class="btn btn-primary" onclick="downloadReport()">
                        <i class="fas fa-download"></i>
                        Download <?php echo strtoupper($format); ?>
                    </button>
                </div>
            </div>

            <!-- Report Header -->
            <div class="report-header">
                <div class="report-info">
                    <p><strong>Generated On:</strong> <?php echo date('d M Y, h:i A'); ?></p>
                    <p><strong>Generated By:</strong> John Doe</p>
                    <p><strong>Report Period:</strong> <?php echo date('d M Y', strtotime($start_date)); ?> - <?php echo date('d M Y', strtotime($end_date)); ?></p>
                    <?php if ($program): ?>
                    <p><strong>Program:</strong> <?php echo ucwords(str_replace('-', ' ', $program)); ?></p>
                    <?php endif; ?>
                    <?php if ($batch): ?>
                    <p><strong>Batch:</strong> <?php echo ucwords(str_replace('-', ' ', $batch)); ?></p>
                    <?php endif; ?>
                </div>
                <div class="report-logo">
                    <img src="<?php echo $base_url; ?>assets/images/logo.png" alt="Softpro Skill Solutions">
                </div>
            </div>

            <!-- Report Content -->
            <div class="report-content">
                <?php
                // Include the appropriate report template based on type
                $template_file = str_replace('-', '_', $type) . '.php';
                if (file_exists($template_file)) {
                    include $template_file;
                } else {
                    echo '<div class="alert alert-warning">Report template not found.</div>';
                }
                ?>
            </div>

            <!-- Report Footer -->
            <div class="report-footer">
                <p>This report was generated on <?php echo date('d M Y'); ?> by the Softpro Skill Solutions Reporting System.</p>
                <p>For any questions or clarifications, please contact the reporting team.</p>
            </div>
        </div>
    </main>

    <script src="<?php echo $base_url; ?>assets/js/main.js"></script>
    <script>
        function downloadReport() {
            // Simulate report download
            alert('Report download started...');
        }
    </script>
</body>
</html> 